# .pre-commit-config.yaml

# Default repository for common hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0 # Use a specific tag or commit hash
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

# Ruff configuration (replaces black, isort, flake8)
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version. Must be kept in sync with pyproject.toml
    rev: v0.4.4
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix, --exit-zero] # Enable auto-fix, soften hook
      # Run the formatter.
      - id: ruff-format
