# Dream.OS Configuration

# Startup mode: 'gui' or 'task'
mode: task # Changed to task mode for testing

# Logging configuration
logging:
  level: INFO # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  # log_file: dream_os.log # Uncomment to enable file logging
  log_dir: logs # Directory to store log files if file logging is enabled

# Core paths
paths:
  # Path to store memory or knowledge base files
  memory: data/memory
  # Path for temporary files or chat logs
  temp: data/temp
  # Path to ChromeDriver cache (managed by webdriver-manager)
  # webdriver_cache: ~/.wdm # Default, usually no need to change

# Example task for 'task' mode
task_details:
  description: "Read the main.py file and create a copy named main_copy.py in the temp directory."
  target_files: ["main.py"] # Example target
  output_path: "data/temp/main_copy.py" # Example output path relative to project root

# --- GUI Settings (If mode is 'gui') ---
gui:
  window_title: "Dream.OS v0.4"
  default_geometry: [100, 100, 1200, 800] # x, y, width, height
  icon_theme: "default" # Placeholder for icon theme selection

# --- Task Runner Settings (If mode is 'task_runner') ---
# (Currently handled via --run-task flag in main.py, might integrate here)
# task_runner:
#  default_planner: "context_planner"

# --- DriverManager Defaults (Can be overridden per instance) ---
driver_manager:
  default_headless: false
  default_undetected: true
  default_wait_timeout: 15 # seconds
  default_session_duration: 3600 # seconds (1 hour)
  # Add other relevant DriverManager defaults

# --- Placeholder for Dream Mode Config ---
# dream_mode:
#   agent_pool: ["researcher", "coder"]
#   objective: "Develop feature X based on specification Y."

# Placeholder for future tool-specific configurations
tools:
  # Example:
  # chatgpt_scraper:
  #   model: "gpt-4"
  #   credentials_file: "chatgpt_cookies.json" 