global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'dream_os_cursor'
    static_configs:
      - targets: ['localhost:8000']
        labels:
          env: 'production'
    metrics_path: '/metrics'
    scheme: 'http'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'cursor_result_listener'

  - job_name: 'dream_os_workflow'
    static_configs:
      - targets: ['localhost:8001']
        labels:
          env: 'production'
    metrics_path: '/metrics'
    scheme: 'http'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'workflow_agent'

  - job_name: 'dream_os_feedback'
    static_configs:
      - targets: ['localhost:8002']
        labels:
          env: 'production'
    metrics_path: '/metrics'
    scheme: 'http'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'feedback_consumer' 